### ISSUE TITLE
Correct Calendar Plot

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/vayu#12]
Currently, Calendar plot does not start from the correct date.

How to reproduce: plot the calendar plot for different years. The output should match the one you get from openAir R package calendar plot (http://davidcarslaw.github.io/openair/reference/calendarPlot.html)

**Comment by apoorvagnihotri** [comment]
019c6e3aa19a5fc1981a78f16ec8d53a55acd073 Corrects this issue.
