### ISSUE TITLE
scatterplot enhancement

### ISSUE THREAD

**Issue by Tanvi-Jain01** [sustainability-lab/vayu#39]
I think scatterPlot code can be enhanced and optimized by making the function more generalized, allowing it to handle any attribute or pollutant, not just the specified ones.

you can view the issue here: https://github.com/Tanvi-Jain01/Delhi-AirQuality-/blob/main/Vayu/Vayu%20Issues/scatterPlot%20issues/scatterPlot%20issue.ipynb

**Comment by nipunbatra** [comment]
@Tanvi-Jain01 - the issue should be self contained. One should not need to look at another repo for the same.

Also, clearly quantify the problems in previous code with examples and showing specific lines of code from existing implementation. Then, propose the new design. 

I'm closing this issue. Please create a new issues with the above mentioned details.
