### ISSUE TITLE
InterpolPlot: Lasso() is giving error

### ISSUE THREAD

**Issue by Tanvi-Jain01** [sustainability-lab/vayu#42]
<img width="737" alt="interpolplot" src="https://github.com/sustainability-lab/vayu/assets/123053700/9964e323-d161-4ae2-92fb-bf03dd9b8c1b">

**Comment by nipunbatra** [comment]
1. What is the code to reproduce this error. Can you create a minimal working example that does not require downloading complex datasets?
2. I recommend never putting screenshots for code and error. Instead use markdown highlighting for code.
3. What error do you get? giving error is not useful enough.
4. What are the proposed solutions.


Closing this issue now. Please open a new issue with corrections suggested above.
